In [1]:
import pandas as pd
import numpy as np

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.tree import DecisionTreeClassifier

In [3]:
df = pd.read_csv('C:\\Users\\EXCELL  COMPUTERS\\Programming_Data_Science\\CSV_Files\\Titanic.csv')

In [4]:
df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [5]:
df.drop(columns=['PassengerId','Name','Ticket','Cabin'],inplace=True)

In [6]:
X_train, X_test, Y_train, Y_test = train_test_split(df.drop(columns = ['Survived']),
                                                   df['Survived'],
                                                   test_size = 0.2,
                                                   random_state=42)

In [7]:
X_train.head(3)

Pclass   Sex   Age  SibSp  Parch    Fare Embarked
331       1  male  45.5      0      0  28.500        S
733       2  male  23.0      0      0  13.000        S
382       3  male  32.0      0      0   7.925        S

In [8]:
Y_train.head(2)

331    0
733    0
Name: Survived, dtype: int64

In [9]:
#imputation transformer
trf1 = ColumnTransformer([
    ('impute_age',SimpleImputer(),[2]),
    ('impute_embarked',SimpleImputer(strategy='most_frequent'),[6])
],remainder='passthrough')

In [10]:
#one hot encoding
trf2 = ColumnTransformer([
    ('ohe_sex_embarked',OneHotEncoder(sparse=False,handle_unknown='ignore'),[1,6])
],remainder='passthrough')

In [11]:
#scaling
trf3 = ColumnTransformer([
    ('scale',MinMaxScaler(),slice(0,10))
])

In [12]:
#feature selection
trf4 = SelectKBest(score_func=chi2, k = 8)

In [13]:
#train the model
trf5 = DecisionTreeClassifier()

### Create Pipe line

In [14]:
pipe  = Pipeline([
    ('trf1',trf1),
    ('trf2',trf2),
    ('trf3',trf3),
    ('trf4',trf4),
    ('trf5',trf5)
])

In [18]:
#Display Pipeline
from sklearn import set_config
set_config(display='diagram')

In [19]:
pipe.fit(X_train, Y_train)

Pipeline(steps=[('trf1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('impute_age', SimpleImputer(),
                                                  [2]),
                                                 ('impute_embarked',
                                                  SimpleImputer(strategy='most_frequent'),
                                                  [6])])),
                ('trf2',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('ohe_sex_embarked',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse=False),
                                                  [1, 6])])),
                ('trf3',
                 ColumnTransformer(transformers=[('scale', MinMaxScaler(),
                                                  slice(0, 10, None))])),
                ('trf4',
                 SelectKBest(k=8,
                             score_func=<function chi2 at 0x0000025C097E54C0>)),
                ('trf5', DecisionTreeClassifier())])

### Explore the pipeline

In [17]:
pipe.named_steps

{'trf1': ColumnTransformer(remainder='passthrough',
                   transformers=[('impute_age', SimpleImputer(), [2]),
                                 ('impute_embarked',
                                  SimpleImputer(strategy='most_frequent'),
                                  [6])]),
 'trf2': ColumnTransformer(remainder='passthrough',
                   transformers=[('ohe_sex_embarked',
                                  OneHotEncoder(handle_unknown='ignore',
                                                sparse=False),
                                  [1, 6])]),
 'trf3': ColumnTransformer(transformers=[('scale', MinMaxScaler(), slice(0, 10, None))]),
 'trf4': SelectKBest(k=8, score_func=<function chi2 at 0x0000025C097E54C0>),
 'trf5': DecisionTreeClassifier()}

In [20]:
Y_pred = pipe.predict(X_test)

In [21]:
Y_pred

array([1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0], dtype=int64)

In [22]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test, Y_pred)

0.6256983240223464

In [23]:
params = {
    'trf5__criterion' : ["gini", "entropy"],
    'trf5__splitter' : ["best", "random"],
    'trf5__max_depth' : [1,2,3,4,5,6]
}

In [24]:
from sklearn.model_selection import GridSearchCV

In [25]:

grid = GridSearchCV(pipe,param_grid=params, scoring='accuracy', cv= 5 )

In [26]:
grid.fit(X_train, Y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('trf1',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('impute_age',
                                                                         SimpleImputer(),
                                                                         [2]),
                                                                        ('impute_embarked',
                                                                         SimpleImputer(strategy='most_frequent'),
                                                                         [6])])),
                                       ('trf2',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('ohe_sex_embarked',
                                                                         OneHotEncoder(handle_unknown='ignore',
                                                                                       sparse=False),
                                                                         [1,
                                                                          6])])),
                                       ('trf3',
                                        ColumnTransformer(transformers=[('scale',
                                                                         MinMaxScaler(),
                                                                         slice(0, 10, None))])),
                                       ('trf4',
                                        SelectKBest(k=8,
                                                    score_func=<function chi2 at 0x0000025C097E54C0>)),
                                       ('trf5', DecisionTreeClassifier())]),
             param_grid={'trf5__criterion': ['gini', 'entropy'],
                         'trf5__max_depth': [1, 2, 3, 4, 5, 6],
                         'trf5__splitter': ['best', 'random']},
             scoring='accuracy')

In [27]:
grid.best_score_

0.6391214419383433

In [28]:
grid.best_params_

{'trf5__criterion': 'gini', 'trf5__max_depth': 2, 'trf5__splitter': 'best'}

### Exporting the pipeline

In [29]:
import pickle
pickle.dump(pipe, open('pipe.pkl','wb'))

In [41]:
pipe2 = pickle.load(open('C:\\Users\\EXCELL  COMPUTERS\\Programming_Data_Science\\SkLearn_Practice\\pipe.pkl','rb'))

In [42]:
X_test.head(2)

Pclass   Sex   Age  SibSp  Parch     Fare Embarked
709       3  male   NaN      1      1  15.2458        C
439       2  male  31.0      0      0  10.5000        S

In [46]:
sample = np.array([2,'male',32.0,0,0,10.5000,'S'],dtype = object).reshape(1,7)

In [48]:
sample

array([[2, 'male', 32.0, 0, 0, 10.5, 'S']], dtype=object)

In [47]:
pipe2.predict(sample)

C:\Users\EXCELL  COMPUTERS\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(
C:\Users\EXCELL  COMPUTERS\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

In [49]:
#So this is easy task for us now
